### ISSUE TITLE
Implementing 6DoF Multi-Body Simulation in OpenFOAM

### ISSUE THREAD

**Issue by wang270020** [hfchen20/foamMooring#2]
Dear Chen,

Hello,

With the help of your project, I have been exploring the implementation of multi-body simulations in OpenFOAM. However, during my attempts across various cases and different versions of OpenFOAM, I managed to achieve RGB (Rigid Body Dynamics) multi-body motion but struggled to simulate multi-body with six degrees of freedom (6DoF).

After reading your paper, I noticed that you achieved some success with 6DoF multi-body motion in OpenFOAM v2212. Could you please provide guidance on how to implement multi-body motion with 6DoF in OpenFOAM? Are there specific steps or configurations needed to achieve this?

Additionally, I observed that the latest waves2Foam update supports up to OpenFOAM v2206. I am curious whether it is possible to use overWaveDyMFoam in OpenFOAM v2212 for computations. If so, how can this be done?

I greatly appreciate your time and assistance!

**Comment by hfchen20** [comment]
- 6DoF multi-body motion
You add multiple entries in `dynamicMeshDict.solvers` for each of the bodies.

- overWaveDyMFoam
Adapt the waveFoam solver to include overset mesh support.

**Comment by wang270020** [comment]
Hello, thank you for your response.

- I have been searching through various resources to implement 6DoFf multi-body overset grid simulation in OpenFOAM and have tried several versions, but unfortunately, all my attempts have failed. Could you please tell me if the following code is in the correct format, or which version supports multi-body motion?
`dynamicFvMesh       dynamicOversetFvMesh;
solvers
{
    Obj1
    {
        solver          sixDoFRigidBodyMotion;
        sixDoFRigidBodyMotionCoeffs
        {
            patches       ;
        }
    }
    Obj2
    {
...
    }
}
`

- Could you please let me know if `waveFoam` can be compiled in OpenFOAM v2212 or higher? Does it require any additional code modifications?

I am extremely thankful for the help you have provided.

**Comment by hfchen20** [comment]
> * I have been searching through various resources to implement 6DoFf multi-body overset grid simulation in OpenFOAM and have tried several versions, but unfortunately, all my attempts have failed. Could you please tell me if the following code is in the correct format, or which version supports multi-body motion?
>   `dynamicFvMesh       dynamicOversetFvMesh; solvers { Obj1 { solver          sixDoFRigidBodyMotion; sixDoFRigidBodyMotionCoeffs { patches       ; } } Obj2 { ... } } `

Yes. That was what I used for the twinFB case in the Ocean Engineering paper.

> * Could you please let me know if `waveFoam` can be compiled in OpenFOAM v2212 or higher? Does it require any additional code modifications?

If you could not compile `waveFoam` straight out of the box for the OpenFOAM version you are using, probably some code changes are necessary. You need to adapt the solver for overset grid anyway.

**Comment by wang270020** [comment]
Thank you for your assistance. I have gained a new perspective on the work, and I will proceed to redesign the cases to achieve the simulation of multi-body motion. I appreciate your help.
