### ISSUE TITLE
Problems about the multi-body 

### ISSUE THREAD

**Issue by smallduan** [hfchen20/foamMooring#3]
Hi @hfchen20 @sanguinariojoe 

I am trying to use the foamMooring to simulate a two-float systerm based on the tut sixdof_2d/overset. However, my computation did not start after initialization. Due to my limited familiarity with overset mesh, I have attached my computation files. I would greatly appreciate any feedback and suggestions from all of you. 

Best regards
Yupeng

[overset_twobody.zip](https://github.com/user-attachments/files/16647100/overset_twobody.zip)

**Comment by hfchen20** [comment]
Could you provide a sketch of the case you want to simulate? It looks like you are attempting a shared mooring setup using 6dof motion library. Personally, I have only run that kind of cases using rigid body dynamics library.

The problem with 6dof shared mooring is that each 6dof body (in the current implementation) has its own mooring restraints, which creates a moordyn system separately. It has no information about other bodies.

**Comment by smallduan** [comment]
Hi @hfchen20 
I want to simulate a float systerm which with a complex mooring systerm as shown bellow:
![image](https://github.com/user-attachments/assets/fb02eb3a-1ea8-4020-a195-e8db7bcf9a2d)
as the figure shows the two small float is apart of the mooring systerm.

"I have only run that kind of cases using rigid body dynamics library." 
For me I find in this issue #2  you say "Yes. That was what I used for the twinFB case in the Ocean Engineering paper." for using overset mesh, and I think my case is like the one you give in the paper so I trying to set the dynamicmeshdict as the issue say, and  because I am not very familar with the dynamic mesh so I trying to simulate the two-float systerm as your paper shows, can you tell me how to set the  rigidBodyMotionCoeffs and restrans for the case? I am struggling with how to set these things in the dictionary because I can hardly find any examples to refer to.

**Comment by smallduan** [comment]
Hi @hfchen20 

I make a case based on rgb_overset. I'm very sorry to bother you. How should I set up the dynamicMeshDict? Are there any examples I can refer to?
[rgb_overset3.zip](https://github.com/user-attachments/files/16649043/rgb_overset3.zip)

**Comment by hfchen20** [comment]
Let it be clear about the case setup in the OE paper: 

- the 6dof motion library can be and was used for the twinFB who are independently moored; 
- only the rgb library was used for the twinFB with a shared mooring.
